### PR TITLE
fix: https://github.com/FasterXML/jackson-datatype-joda/issues/93

### LINKED ISSUE #93: ADJUST_DATES_TO_CONTEXT_TIME_ZONE got wrong result when parse string contains zone id
Version: 2.8.8

```java
  public static class Foo {

    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private DateTime jodaDateTime;

    public DateTime getJodaDateTime() {
      return jodaDateTime;
    }

    public void setJodaDateTime(DateTime jodaDateTime) {
      this.jodaDateTime = jodaDateTime;
    }
  }

  private static void main(String[] args) throws IOException {

    ObjectMapper objectMapper = new ObjectMapper();
    objectMapper.registerModule(new JodaModule());
    objectMapper.enable(DeserializationFeature.ADJUST_DATES_TO_CONTEXT_TIME_ZONE);

    System.out.println(objectMapper.readValue("{\"jodaDateTime\":\"2017-01-01 01:01:01[Asia/Shanghai]\"}", Foo.class).getJodaDateTime());

  }
```

The input param is `"2017-01-01 01:01:01[Asia/Shanghai]"`, but the result is `2017-01-01T09:01:01.000+08:00`. The correct result should be `2017-01-01 01:01:01.000Z`.

### PR DESCRIPTION
**Pull request by chanjarster**
Fix #93

### CODE REVIEW

**Comment by chanjarster** [comment]
Oops unit test failed, I'll fix this and open another pull request

**Comment by chanjarster** [comment]
The unit test failure on `MiscDeserializationTest#testSimpleDateTimeZone` is not caused by my commit, so reopen it.

**Comment by chanjarster** [comment]
@cowtowncoder Ok, I'll do this on next workday

**Comment by chanjarster** [comment]
@cowtowncoder The contributor agreement has been email to `info` at fasterxml dot com

**Comment by cowtowncoder** [comment]
Perfect, CLA received.

**Comment by cowtowncoder** [comment]
Hmmh. But one of the new tests seem to fail now. Odd...

**Comment by cowtowncoder** [comment]
Found it; I think fix needed a slight change, after which test passes.

**Pull request merged**
