### PR TITLE
add no-arg constructor for DateTimeDeserializer

### PR DESCRIPTION
**Pull request by abbychau**
issue #124

### CODE REVIEW

**Comment by cowtowncoder** [comment]
Quick question here... I am bit confused: constructor being added takes 1 argument; it's not a no-args constructor. I should have noticed and mentioned this earlier. This would not work with annotations yet, only truly 0-argument constructor would.

**Comment by abbychau** [comment]
sorry. You are right. I made a mistake. I just changed that to a 0-arg.

**Comment by cowtowncoder** [comment]
Ok; this might work, but I think one thing we really need here is a unit test, to verify specified usage works.
Especially since is a new feature at this point, something that did not work before.

Would it be possible to add that? Apologies for not asking for this earlier.

**Comment by abbychau** [comment]
@cowtowncoder  just added. Could you check whether the test case matches the standard?

**Comment by cowtowncoder** [comment]
Looks good. Thank you! Will merge for 2.14.

**Pull request merged**
