### PR TITLE
Add support for JsonFormat.Feature.ADJUST_DATES_TO_CONTEXT_TIME_ZONE

### LINKED ISSUE #87: Add support for JsonFormat.Feature.ADJUST_DATES_TO_CONTEXT_TIME_ZONE
https://github.com/FasterXML/jackson-annotations/issues/95 needs to be implemented in joda module

### PR DESCRIPTION
**Pull request by joxerTMD**
Add support for JsonFormat.Feature.ADJUST_DATES_TO_CONTEXT_TIME_ZONE

### CODE REVIEW

**Comment by joxerTMD** [comment]
I think You've somehow missed this changes because they are not in the master branch now.

**Comment by cowtowncoder** [comment]
I must have accidentally closed the PR before merging it. Should be merged now.

**Comment by cowtowncoder** [comment]
Ummh. Also, I will rewrite this, I don't actually like removal of immutability or addition of redundant set of classes.

**Comment by joxerTMD** [comment]
Ok, no problem :) It's all up to you to decide how it should be written :)
Btw i don't think there were any significant immutability removal because no public methods were returning Setup classes. But maybe i've gone too far trying to refactor these. Just was trying to keep the code easy to understand :)

**Comment by cowtowncoder** [comment]
@joxerTMD I agree in that there was no real danger as it's included internally. I should have just suggested that addition of N-parameter constructors is also fine, esp. when needed. So it was more just keeping actual change limited. Thank you for the patch, the important thing is to get the new feature(s) added!

**Comment by joxerTMD** [comment]
Hello again! One more little thing has just came into my mind. When you changed the constructor's signature from JacksonJodaDateFormat(JacksonJodaDateFormat, Boolean) to JacksonJodaDateFormat(JacksonJodaDateFormat(JacksonJodaDateFormat, Boolean, Boolean), joda module had lost its backwards compatibility because it its a public constructor. I don't think that many people use it for their own purposes but it's theoretically possible. So maybe we should keep two of them?I can prepare a PR if its needed.

**Comment by joxerTMD** [comment]
Hello again! One more little thing has just came into my mind. When you changed the constructor's signature from JacksonJodaDateFormat(JacksonJodaDateFormat, Boolean) to JacksonJodaDateFormat(JacksonJodaDateFormat(JacksonJodaDateFormat, Boolean, Boolean), joda module had lost its backwards compatibility because it its a public constructor. I don't think that many people use it for their own purposes but it's theoretically possible. So maybe we should keep two of them?I can prepare a PR if its needed.

**Comment by joxerTMD** [comment]
Oh. I see that it already has been fixed. Apology for disturbing you.

**Comment by cowtowncoder** [comment]
Good point and not a problem at all: I'd rather potential problems be reported (even if redundant) than missing things that break compatibility, since these problems are really frustrating for anyone using the library.

**Comment by cowtowncoder** [comment]
Also, in retrospect, constructors should be `protected`, not `public` but can't really change that safely either.

**Pull request merged**
